### PR TITLE
[13.0][MIG] hr_timesheet_sheet_autodraft_project

### PR DESCRIPTION
**Pull request by davejames**

### CODE REVIEW

**Comment by davejames** [comment]
changing this to WIP, I will migrate the hr_timesheet_sheet_autodraft module before resubmitting this one

**Comment by davejames** [comment]
> changing this to WIP, I will migrate the hr_timesheet_sheet_autodraft module before resubmitting this one

Actually, I realise now I already submitted a PR for that module at https://github.com/OCA/timesheet/pull/345. Unfortunately I realised after I re-did the migration but never mind.

This PR depends on that one for the tests to pass.

**Comment by davejames** [comment]
Updated to include 4cf886239cde5ee0a99cfdbd9170f9f36bf866aa

Will rebase after https://github.com/OCA/timesheet/pull/345 is merged.

**Comment by davejames** [comment]
This migration now passes tests since the hr_timesheet_sheet_autodraft module is available

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Thanks, merging as it's a trivial migration

**Pull request merged**
