### PR TITLE
[10.0][FIX] hr_timesheet_task: Only select tasks which belong to selected project

### PR DESCRIPTION
**Pull request by benwillig**

### CODE REVIEW

**Review by Laurent-Corron — APPROVED** [review]

**Review by apineux — APPROVED** [review]

**Review by baimont — APPROVED** [review]

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by benwillig** [comment]
@pedrobaeza I think this can be merged without extra approvals.

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Unfortunately, travis fails on merging

**Pull request merged**
