### PR TITLE
[12.0][ADD] hr_utilization_analysis: review utilization in graph and pivot

### PR DESCRIPTION
**Pull request by alexey-pelykh**
To view analysis using Utilization Analysis Wizard:
#. Go to *Timesheets > Reporting > Utilization Analysis Wizard*.
#. Configure the data set and click "View".

To view analysis using Utilization Analysis Wizard on a specific set of Employees:
#. Go to *Employees > Employees*.
#. Select employees that should be used in the analysis
#. Press the *Action > View Utilization Analysis* button
#. Configure the data set and click "View".

To view analysis using Utilization Analysis Wizard on a specific set of Departments:
#. Go to *Employees > Departments*.
#. Select departments that should be used in the analysis
#. Press the *Action > View Utilization Analysis* button
#. Configure the data set and click "View".

With `project_timesheet_holidays` module installed, leaves are not taken into
account: for a single 4-hour entry on specific day with 8 working hours and
4 hours of leaves, capacity would be calculated as 8 hours and utilization
would be calculated as 100%.

Without `project_timesheet_holidays` module installed, leaves are taken into
account: for a single 4-hour entry on specific day with 8 working hours and
4 hours of leaves, capacity would be calculated as 4 hours and utilization
would be calculated as 100%.

image
image

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@aheficent @mreficent @nikul-serpentcs if would be great to get your reviews, if you don't mind

**Review by AaronHForgeFlow — COMMENTED** [review]
Looks great to me. Just some comment. In the readme we refer to utilization but in reality the report is called "Capacity Analysis". And also the name of the module is confusing. But it is ok to me just to update the readme. 

I hope to have an integration with #163 soon :smiley:

**Comment by alexey-pelykh** [comment]
To be exact, "Timesheet / Capacity" is "Utilization", yet for consistency I'd rename it to "Utilization" in menu.

**Comment by alexey-pelykh** [comment]
@aheficent ready for re-review :)

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Awesome

**Review by tarteo — APPROVED** [review]
Phenomenal!!!

**Comment by alexey-pelykh** [comment]
@pedrobaeza CI fails until #181 is merged

**Pull request merged**
