### PR TITLE
[16.0][MIG] hr_timesheet_task_stage: Migration to version 16.0

### PR DESCRIPTION
**Pull request by stefan-tecnativa**
cc @Tecnativa TT43229

This PR superseeds #587 

@ernestotejeda @CarlosRoca13 please review!

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
Tested :+1:

**Comment by DorianMAG** [comment]
Hi,
Tested on runboat.
Seems to be good

**Review by DorianMAG — APPROVED** [review]
Thx for this work.
Tested on runboat.
LGTM

**Pull request merged**
