### PR TITLE
fix pep8

### PR DESCRIPTION
**Pull request by gurneyalex**
line max length now 79 char, not 80

one of the refactoring involved renaming xxxx_pool variables to xxxx_obj which is the generally used convention and 1 char shorter.

### CODE REVIEW

**Comment by eLBati** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1: 

Thanks.

**Comment by bwrsandman** [comment]
> one of the refactoring involved renaming xxxx_pool variables to xxxx_obj which is the generally used convention and 1 char shorter. 

Why? `_obj` seems much less clear as to what that variable is, I much prefer `_pool`. I don't see how gaining one character is worth that. Plus `_obj` sounds a lot more like a browse object than the class-like object returned from the pool/registry.

**Comment by pedrobaeza** [comment]
`_obj` is current convention, so I see logic to change this. One char saving is not the main reason I suppose.

**Comment by nbessi** [comment]
:+1:

**Pull request merged**
