### PR TITLE
[11.0][FIX] hr_timesheet_sheet: fix sheet_id calculation

### LINKED ISSUE #190: [11.0][BUG] hr_timesheet_sheet: sheet_id not correct when modifying the timesheet
Create a new fresh DB and install `hr_timesheet_sheet`.

Create a weekly timesheet sheet for current week, eg.: 02/25/2019 to 03/03/2019 (Week9).
Create a weekly timesheet sheet for previous week, eg.: 02/18/2019 to 02/24/2019 (Week8).

Go to "Timesheet -> All Timesheets".
Create a new timesheet (`account.analytic.line`) with the date of today (eg.: 02/25/2019). Save.
Edit the timesheet and set a date of previous week (eg.: 02/18/2019). Save.

Open the Week9 weekly sheet: the timesheet line is displayed in the Details tab (should be not).
Open the Week8 weekly sheet: the timesheet line is displayed in the Summary tab but is not displayed in the Details tab.

### PR DESCRIPTION
**Pull request by astirpe**
Fixes #190

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM 👍 Is it possible to add a test case for the scenario?

**Comment by astirpe** [comment]
@alexey-pelykh I don't have so much extra time for writing a test for it. A manual test on Runbot can quickly prove that the issue is fixed.
This PR is a high prio in my opinion. I hope will be merged soon.

**Comment by alexey-pelykh** [comment]
@astirpe I'm not going to block anyhow this PR, as it's valid, though it would be great to have a unit test to help future migrators to do their job

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
Tested on runbot :+1:

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
