### PR TITLE
[12.0][FIX] hr_timesheet_sheet

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This PR is the literal forward port of https://github.com/OCA/timesheet/pull/251 and https://github.com/OCA/timesheet/pull/237.

I played a bit to try to implement the server-side forms in the tests, but I ended up abandoning the idea 😥

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@astirpe @alexey-pelykh

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@mreficent if possible, give me some insights what you've tried to do as server-side form testing?

**Comment by MiquelRForgeFlow** [comment]
[server-side form](https://github.com/odoo/odoo/blob/12.0/odoo/tests/common.py#L1013L1084) (as you can see, it's still incomplete (partial), and thus, still needs to be improved more to be used in our tests)

**Review by astirpe — APPROVED** [review]
Code review only (I didn't test it).

**Pull request merged**
