### PR TITLE
[FIX]hr_timesheet_sheet : unit amount will display in formate hr:minute

### PR DESCRIPTION
**Pull request by bizzappdev**
Adding float_time widget so it will be more readable.

### CODE REVIEW

**Review by astirpe — APPROVED** [review]
Please rebase the branch

**Review by MiquelRForgeFlow — APPROVED** [review]
Please, rebase

**Comment by bizzappdev** [comment]
rebase done.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza

**Comment by astirpe** [comment]
@bizzappdev will you port this fix to V12?

**Comment by bizzappdev** [comment]
@astirpe  it is already done by today I will create PR

**Comment by bizzappdev** [comment]
#253 created for 12.0

**Pull request merged**
