### PR TITLE
7.0 localized date

### PR DESCRIPTION
**Pull request by charbeljc**
Supersedes https://github.com/OCA/hr-timesheet/pull/25

### CODE REVIEW

**Comment by eLBati** [comment]
:+1: LGTM

**Comment by mdietrichc2c** [comment]
:+1: LGTM

**Comment by charbeljc** [comment]
Hi @tafaRU i updated your PR according to @mdietrichc2c and @eLBati suggestion, could you review this, so it can be merged ? thx

**Comment by mv-organizeit** [comment]
:+1:

**Comment by Olivier-LAURENT** [comment]
:+1:

**Comment by tafaRU** [comment]
@charbeljc sorry about the delay in answering you but I had 2 days off :wink:

Thanks!

**Pull request merged**
