### PR TITLE
[11.0][FIX] hr_timesheet_sheet: deleting all lines

### PR DESCRIPTION
**Pull request by astirpe**
Fixes https://github.com/OCA/hr-timesheet/issues/198

### CODE REVIEW

**Review by MiquelRForgeFlow — APPROVED** [review]
tested on runbot :+1: 
How have you found this?

**Comment by astirpe** [comment]
Apparently the travis failure doesn't occur in https://github.com/OCA/hr-timesheet/pull/207.

Travis failure is:
```
Exception while validating constraint
Traceback (most recent call last):
  File "/home/travis/odoo-11.0/odoo/models.py", line 1037, in _validate_fields
    check(self)
  File "/home/travis/build/OCA/hr-timesheet/hr_timesheet_sheet_attendance/models/hr_attendance.py", line 91, in _check_timesheet
    "Ask your manager to reset it before adding attendance."
odoo.exceptions.UserError: ('You can not enter an attendance in a submitted timesheet. Ask your manager to reset it before adding attendance.', '')
Exception while validating constraint
Traceback (most recent call last):
  File "/home/travis/odoo-11.0/odoo/models.py", line 1037, in _validate_fields
    check(self)
  File "/home/travis/build/OCA/hr-timesheet/hr_timesheet_sheet_attendance/models/hr_attendance.py", line 91, in _check_timesheet
    "Ask your manager to reset it before adding attendance."
odoo.exceptions.UserError: ('You can not enter an attendance in a submitted timesheet. Ask your manager to reset it before adding attendance.', '')
Exception while validating constraint
Traceback (most recent call last):
  File "/home/travis/odoo-11.0/odoo/models.py", line 1037, in _validate_fields
    check(self)
  File "/home/travis/build/OCA/hr-timesheet/hr_timesheet_sheet_attendance/models/hr_attendance.py", line 108, in _check_timesheet
    "outside the current timesheet dates."))
odoo.exceptions.UserError: ('You can not enter an attendance date outside the current timesheet dates.', '')
```

**Comment by MiquelRForgeFlow** [comment]
> Apparently the travis failure doesn't occur in #207.

It's strange.

**Comment by MiquelRForgeFlow** [comment]
Could you cherry-pick [[FIX] hr_timesheet_sheet_attendance: AccessError](https://github.com/OCA/hr-timesheet/pull/201/commits/609aac49310920ee314002999798833f128b12fc) to see if it also greenifies this PR?

**Comment by astirpe** [comment]
Yes, it's green now

**Comment by MiquelRForgeFlow** [comment]
Good :+1:

**Comment by astirpe** [comment]
Superseded by https://github.com/OCA/hr-timesheet/pull/207

**Pull request closed without merging**
