### PR TITLE
[15.0][IMP] hr_timesheet_task_stage: Change string by title in buttons at tree level

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa 

ping @pedrobaeza @sergio-teruel

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
@sbidoul runboat seems to not being triggered on pull requests

**Comment by sbidoul** [comment]
Always blame GitHub first ;)

**Comment by sbidoul** [comment]
https://www.githubstatus.com/

**Comment by pedrobaeza** [comment]
:facepalm:

**Comment by pedrobaeza** [comment]
The column is still taking more space than needed:

Selección_034

Please check any way to limit its width.

**Comment by pedrobaeza** [comment]
Already fixed in #536. Sorry for the overlapping.

**Pull request closed without merging**
