### PR TITLE
[14.0][IMP] hr_timesheet_activity_begin_end: missing fields in task views

### PR DESCRIPTION
**Pull request by dalonsod**
New `time_start` and `time_stop` fields are not shown in task form, this PR adds them.

### CODE REVIEW

**Comment by dalonsod** [comment]
@davejames @schhatbar-initos could you review? Thanks!

@CRogos this improvement could be (manually) added to v16 migration

**Review by davejames — APPROVED** [review]
LGTM. Code review only

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Something is wrong with this PR that halts the bot. Will check it in detail tomorrow.

**Comment by dalonsod** [comment]
Hello @nimarosa , absolutely not sure but at least there's an error that could be a timezone issue:

imagen

So could you simply try merge again?

**Comment by nimarosa** [comment]
Let's try again 

/ocabot merge patch

**Pull request merged**
