### PR TITLE
[12.0][FIX] hr_timesheet_sheet_role: avoid creation of roles in timesheet sheet lines

### PR DESCRIPTION
**Pull request by astirpe**
This change was asked by a customer.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
I'd agree that this causes potentially bad entries

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@MiquelRForgeFlow same story here I believe?

**Comment by MiquelRForgeFlow** [comment]
Yeah, a glue module is needed here instead (with auto_install=True) when the two related modules are installed.

**Comment by astirpe** [comment]
This is already a glue module :thinking:

**Comment by alexey-pelykh** [comment]
Yep, that's also correct :) I have a mixed opinion on this. On one hand - people who can create roles can easily mess up, on other hand - why are they so careless? This "Create And Edit" feature of Odoo gives us a headache every now and then :|

**Comment by astirpe** [comment]
Question is: should an employee create roles while filling its timesheet?
I don't think it's a good idea to allow the creation of roles directly from timesheet sheet lines.

**Comment by alexey-pelykh** [comment]
Regular employee should not have even permission in the first place. Manager who has those permissions - probably should not do that in 80% of cases. That's why here I approved. Task/Projects are different "nature" of entity in comparison to roles

**Review by MiquelRForgeFlow — APPROVED** [review]
ok :+1:

**Pull request merged**
