### PR TITLE
[14.0][MIG] project_task_stage_allow_timesheet

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Comment by sergiocorato** [comment]
@alexey-pelykh are you still interested in this module?

**Comment by alexey-pelykh** [comment]
@sergiocorato why there are two modules in this migration?

**Comment by sergiocorato** [comment]
> @sergiocorato why there are two modules in this migration?

Probably I get the wrong upstream, I've fixed.

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
