### PR TITLE
[14.0][IMP] hr_timesheet_sheet: Screenshot added for quick understanding

### PR DESCRIPTION
**Pull request by tarbib**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please include the image here in the folder, and don't use enterprise interface, but community one.

**Comment by tarbib** [comment]
@pedrobaeza done thanks

**Comment by pedrobaeza** [comment]
Can you squash the 3 commits into one?

**Comment by tarbib** [comment]
@pedrobaeza done thanks

**Review by pedrobaeza — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by hkapatel-initos — APPROVED** [review]
LGTM

**Pull request merged**
