### PR TITLE
[12.0][ADD] project_timesheet_holidays_integrity: ensure and restore data integrity

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This module ensures data integrity between Leaves and generated Timesheets, as
well as allows to restore data integrity.

To restore data integrity from Timesheets to Leaves:
#. Go to *Timesheets > Timesheet > All Timesheets*.
#. Select timesheet lines of interest and perform *Action > Restore data integrity with Leaves*.

To restore data integrity from Leaves to Timesheets:
#. Go to *Leaves > Managers > All > Leaves*.
#. Select leaves of interest and perform *Action > Restore data integrity with Timesheets*.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Relates to https://github.com/odoo/odoo/issues/30854

**Comment by alexey-pelykh** [comment]
Hopefully, will eventually become not needed after https://github.com/odoo/odoo/pull/30863 is merged

**Review by artemsenko — APPROVED** [review]
Functional tests

**Review by sweenya — APPROVED** [review]
Functional review

**Pull request closed without merging**
