### PR TITLE
[15.0][MIG] hr_timesheet_task_required

### PR DESCRIPTION
**Pull request by houssine78**

### CODE REVIEW

**Comment by houssine78** [comment]
@sbidoul I get an error on runboat which seems to unralated to the PR

image

**Comment by pedrobaeza** [comment]
See https://github.com/sbidoul/runboat/issues/48

**Comment by houssine78** [comment]
Hi @benwillig seems you're marked as you haven't signed the OCA CLA

**Comment by yankinmax** [comment]
@houssine78 can you pls give an access to your timesheet repo? I want to update this PR with the fix. THX
or just update it with the fix:
```
<record id="project_invoice_form" model="ir.ui.view">
    <field name="name">project.project.view.form</field>
    <field name="model">project.project</field>
    <field name="inherit_id" ref="hr_timesheet.project_invoice_form" />
    <field name="arch" type="xml">
        <xpath expr="//div[@id='timesheet_settings']" position="after">
            <div
                class="col-lg-6 o_setting_box"
                id="timesheet_task_settings"
                attrs="{'invisible': [('allow_timesheets', '=', False)]}"
            >
                <div class="o_setting_left_pane">
                    <field name="is_timesheet_task_required" class="oe_inline" />
                </div>
                <div class="o_setting_right_pane">
                    <label for="is_timesheet_task_required" />
                    <div class="text-muted">
                        Set tasks on timesheet as a mandatory field
                    </div>
                </div>
            </div>
        </xpath>
    </field>
</record>
```
And also, don't forget to change version numbers across the files from 14.0 to 15.0, and 14-0 to 15-0

**Comment by houssine78** [comment]
Hi @yankinmax,
I just give you the access.

Thank you

**Comment by yankinmax** [comment]
@alexey-pelykh

**Review by alexey-pelykh — APPROVED** [review]

**Comment by houssine78** [comment]
thank you @yankinmax

**Comment by yankinmax** [comment]
> thank you @yankinmax

same to you)

**Pull request merged**
