### PR TITLE
[14.0] [MIG] hr_timesheet_sheet_no_create: Migration to 14.0

### PR DESCRIPTION
**Pull request by alissonjns**
@marcelsavegnago @kaynnan @WesleyOliveira98

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional review. I can create projects an tasks in runboat:

new_project

**Comment by marcelsavegnago** [comment]
ping @kaynnan

**Review by kaynnan — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
I did a second review. It is True you cannot create projects nor tasks for the timesheet lines. But I can still create them from the "Select Project" (add_line_project_id) field and "Select Task" (add_line_task_id). Is there a reason why that part is not covered? Or will you accept to introduce this improvement?

**Comment by kaynnan** [comment]
@AaronHForgeFlow I believe that the behavior is as it should be, as we have the same effect in runboat v12 too, if an improvement is really needed, it is possible through another PR focusing on IMP

Runboat 14.0:

image


Runboat v12.0:

image

**Comment by kaynnan** [comment]
@AaronHForgeFlow I carried out the tests and the same behavior occurred in runboat v12, in case of improvements I believe it would be better in another PR focusing on IMP, as this would facilitate identification and carry out the cherry-pick for v12 as well.

Runboat 14.0:

image


Runboat v12.0:

image

**Review by AaronHForgeFlow — APPROVED** [review]
As per comments it works the same as in previous versions. So ok to me

**Comment by kaynnan** [comment]
ping @OCA/human-resources-maintainers

**Pull request merged**
