### PR TITLE
[14.0] [mig] hr_timesheet_sheet_policy_project_manager

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Comment by fshah-initos** [comment]
Travis fails as the depended module PR #434 is not merged yet.

**Comment by fshah-initos** [comment]
@astirpe can you please add the review here.

**Comment by fshah-initos** [comment]
It would ne nice if someone can add review here.

**Comment by alexey-pelykh** [comment]
Why don't you follow https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0 ? In terms that change of version should happen in migration commit?

**Comment by fshah-initos** [comment]
I have updated according to guideline.

**Review by alexey-pelykh — APPROVED** [review]

**Review by dsolanki-initos — APPROVED** [review]
LGTM. Code review and Functional Tests

**Pull request merged**
