### PR TITLE
[12.0] [ADD] sale_timesheet_purchase: Backport the module from v13 to v12.

### PR DESCRIPTION
**Pull request by Chandresh-SerpentCS**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is this one an Odoo module?

**Comment by max3903** [comment]
@pedrobaeza Yes

**Comment by pedrobaeza** [comment]
Then you should:

- Do an initial commit with the stuff copied from Odoo, and attributing info@odoo.com or similar.
- Add the second one with the needed changes.
- Add the disclaimer in the README.

You can check https://github.com/OCA/manufacture/pull/501 as example.

**Comment by Chandresh-SerpentCS** [comment]
Added new PR #379 with modification.

**Pull request closed without merging**
