### PR TITLE
[ADD] sale_timesheet_analytic_propagation: update timesheet analytic …

### PR DESCRIPTION
**Pull request by edlopen**
…account from task.

This module allows to update the timesheet's analytic account when the task related to it changes the analytic account. This only happens if the timesheet is not invoiced yet.

@moduon MT-5142

### CODE REVIEW

**Comment by edlopen** [comment]
This video made by @rafaelbn explains accurately how this module works. https://www.loom.com/share/89d69fc8f4354c41ba89b06853cace93?sid=574bf3de-77d6-433f-bcab-6ade4bb3cd53

**Comment by edlopen** [comment]
In this PR I've include some suggestions from [this one](https://github.com/OCA/timesheet/pull/637).

**Comment by edlopen** [comment]
@Shide @yajo @EmilioPascual @rafaelbn @alexey-pelykh please review, if you can.

**Comment by yajo** [comment]
> In this PR I've include some suggestions from [this one](https://github.com/OCA/timesheet/pull/637https://github.com/OCA/timesheet/pull/637).

Broken link.

**Review by yajo — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
👍🏼 Thank you!

Please @edlopen , review the comments of @alexey-pelykh in the previous PR and answer to him here in this PR 🙏🏼 😄 

He was kind, reviewing the PR and we should answer him and attend his comments if we all agree. ❤️ 

Thank you!

**Review by alexey-pelykh — APPROVED** [review]

**Comment by edlopen** [comment]
Thank you @alexey-pelykh . Could you merge this PR please?

**Pull request merged**
