### PR TITLE
[13.0][FIX] Typo

### PR DESCRIPTION
**Pull request by ypapouin**
Same as https://github.com/OCA/timesheet/pull/419

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Comment by ypapouin** [comment]
Any idea why the merge fails ?

**Comment by pedrobaeza** [comment]
pre-commit needs a revamp. @joao-p-marques can you please put a PR fixing it?

**Pull request merged**
