### PR TITLE
[12.0][ADD] hr_timesheet_sheet_autodraft: automatically create sheets

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This module adds option to auto-draft Timesheet Sheets whenever a Timesheet
entry is created or modified to ensure it's covered by a relevant Timesheet
Sheet.

### CODE REVIEW

**Review by sweenya — APPROVED** [review]
Functional test

**Comment by alexey-pelykh** [comment]
@astirpe @MiquelRForgeFlow any interest in such feature?

**Comment by astirpe** [comment]
Yes, I'm interested. Some time ago I developed internally a similar module that was automatically creating draft timesheets sheets by a cron job, instead of waiting for a timesheet entry to be created or modified.
:+1:

**Review by sweenya — APPROVED** [review]
Functional test

**Review by YegorOkhotnikov — APPROVED** [review]
Functional test

**Pull request merged**
