### PR TITLE
[14.0] [mig] sale_timesheet_rounded

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
LGTM

**Comment by fshah-initos** [comment]
@pedrobaeza Can you please review this PR?

**Comment by fshah-initos** [comment]
@TDu will you please review this PR?

**Comment by fshah-initos** [comment]
@j-zaballa Is it possbile to get a review here?

**Comment by fshah-initos** [comment]
It would be really great if someone can add reviews here.

**Review by bosd — APPROVED** [review]
Funtional test LGTM :+1:

**Comment by fshah-initos** [comment]
@pedrobaeza can you please merge this?

**Pull request merged**
