### PR TITLE
[ADD] Module 'hr_timesheet_sheet_import_accounts'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
New module to allow faster completion of Timesheets. See http://www.eficent.com/blog_en/timesheet-improvements-in-odoo-import-accounts-from-last-timesheet/ for a functional description.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi @jbeficent ,

Thanks for the contrib ! Can you check the Travis please ? Once good, you get my :+1: ! Very useful small & smart module, I'm eager to use it ;)

Regards,

Joël

**Comment by JordiBForgeFlow** [comment]
Hi  @jgrandguillaume I de-flake8'ed. However an error in the YML tests remains. It seems to me that it is not related to this module, though. This module does not implement any test, or affects to existing tests of other modules in the changes it incorporates.

**Comment by mdietrichc2c** [comment]
Hello @jbeficent ; it seems that there are a few more issues on this PR than a test failing:

`./hr_timesheet_sheet_import_accounts/__openerp__.py:48:2: W292 no newline at end of file`
`./hr_timesheet_sheet_import_accounts/model/hr_timesheet_sheet.py:24:1: F401 'fields' imported but unused`
`./hr_timesheet_sheet_import_accounts/model/hr_timesheet_sheet.py:26:1: E302 expected 2 blank lines, found 1`
`./hr_timesheet_sheet_import_accounts/model/hr_timesheet_sheet.py:36:80: E501 line too long (83 > 79 characters)`
`./hr_timesheet_sheet_import_accounts/model/hr_timesheet_sheet.py:105:60: F812 list comprehension redefines 'timesheet_id' from line 98`

for PEP8/Flake8 issues. The `from lxml import etree` error is unrelated, though.

Can you please fix the PEP8 errors on this PR?

**Comment by JordiBForgeFlow** [comment]
Thanks @mdietrichc2c. Fixed.

**Comment by mdietrichc2c** [comment]
Runbot is in warning, Travis is green. LGTM :+1:

**Comment by charbeljc** [comment]
On runbot:

2015-06-01 13:37:20,961 8618 WARNING 2947781-20-03707c-all openerp.osv.orm: No such field(s) in model ir.values: object.
Should be corrected by this commit: https://github.com/OCA/hr-timesheet/commit/17b7690a466c445fc9c99597546cdb351586f466

LGTM :+1:

**Comment by pedrobaeza** [comment]
Merging as it seems all is correct.

**Pull request merged**
