### PR TITLE
[10.0][hr_timesheet_task] Add domain for task_id in timesheet sheet details tab

### PR DESCRIPTION
**Pull request by florian-dacosta**
Restrict the task choice depending on the project.
It seems it is already done in v12.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by bealdav** [comment]
little problem with transiflex on travis. 
Seems misconfigured .travis.yml file

**Comment by bealdav** [comment]
I confirm 
https://github.com/OCA/timesheet/blob/12.0/.travis.yml
https://github.com/OCA/timesheet/blob/10.0/.travis.yml

**Review by bguillot — APPROVED** [review]

**Review by mourad-ehm — APPROVED** [review]

**Comment by dreispt** [comment]
@florian-dacosta Can you resolve the conflicts, please?

**Comment by florian-dacosta** [comment]
Hello @dreispt Sorry for the delay, I am seeing this conflict only now...
Seems the bug has been resolved by https://github.com/OCA/timesheet/pull/309 which is the source of the conflict.

So it is all good, I just close the PR!

**Pull request closed without merging**
