### PR TITLE
[NEW] hr_timesheet_time_restriction: Add new module

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by elvise** [comment]
@GabbasovDinar can you fix runboat ?

**Comment by GabbasovDinar** [comment]
> @GabbasovDinar can you fix runboat ?

@elvise the error on runboat related with another module: KeyError: 'limit_role_to_assignments'

**Comment by francesco-ooops** [comment]
@GabbasovDinar the same module is not resulting in any error in this pr in the same repo: #487 
maybe a rebase can help?

**Comment by GabbasovDinar** [comment]
> the same module is not resulting in any error in this pr in the same repo: #487
> maybe a rebase can help?

yes, but this module for 12.0

**Comment by ivs-cetmix** [comment]
Ok probably we can open another PR, fix the troublesome module and then try again

**Comment by GabbasovDinar** [comment]
@elvise @francesco-ooops @isserver1 I opened new PR for 14.0 https://github.com/OCA/timesheet/pull/496

**Pull request closed without merging**
