### PR TITLE
[12.0][IMP] hr_timesheet_sheet: _get_subscribers hook

### PR DESCRIPTION
**Pull request by alexey-pelykh**
cc @MiquelRForgeFlow @astirpe one more hook, fasttracking

### CODE REVIEW

**Comment by pedrobaeza** [comment]
AFAIK, there are standard methods for this in mail.thread.

**Comment by alexey-pelykh** [comment]
@pedrobaeza you mean method to get who is subscribed? This one is about who should be subscribed

**Comment by pedrobaeza** [comment]
You have https://github.com/odoo/odoo/blob/4a1e120cc542cb6c92ce6d514a0e849bfab8de4f/addons/mail/models/mail_thread.py#L1758 for suggesting recipients and https://github.com/odoo/odoo/blob/12.0/addons/mail/models/mail_thread.py#L2315 for auto-adding followers

**Comment by alexey-pelykh** [comment]
Oh, neat! Looks promising, I'll try to accommodate that sometime soon

**Pull request merged**
