### PR TITLE
[12.0][ADD] hr_timesheet_sheet: policies

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Supersedes https://github.com/OCA/timesheet/pull/284, depends on https://github.com/OCA/timesheet/pull/290

@aheficent @mreficent @astirpe @CasVissers @i-vyshnevska please preview

### CODE REVIEW

**Comment by astirpe** [comment]
Why is `hr_timesheet_sheet_period` needed?

**Comment by MiquelRForgeFlow** [comment]
@astirpe It seems https://github.com/OCA/timesheet/pull/290 is included here by error.

**Comment by alexey-pelykh** [comment]
@astirpe @mreficent because of bug in `hr_timesheet_sheet_period` tests will fail, see #290

**Review by artemsenko — APPROVED** [review]
Functional test

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
Waiting for https://github.com/OCA/timesheet/pull/290 then rebase then merge

**Pull request merged**
