### PR TITLE
[16.0][MIG] hr_timesheet_sheet_policy_project_manager: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT43227

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @CarlosRoca13  , @pedrobaeza  Please review.

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Please squash administrative commits

**Comment by Yadier-Tecnativa** [comment]
> Please squash administrative commits

Done, Thanks for the review.

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by CarlosRoca13** [comment]
please review changes :) @pedrobaeza @chienandalu

**Review by chienandalu — APPROVED** [review]
Code and functional :+1:

**Pull request merged**
