### PR TITLE
[10.0] port hr_timesheet_task

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by benwillig — APPROVED** [review]

**Comment by ghost** [comment]
@ThomasBinsfeld @Billolha @adrienpeiffer @benwillig Can we merge this pull request ? It has been in production for 1 month in one of my projects and works properly.

**Review by adrienpeiffer — APPROVED** [review]
:+1: (Functional testing)

**Review by ThomasBinsfeld — APPROVED** [review]
Functional tests

**Comment by ghost** [comment]
Thanks! I merge

**Pull request merged**
