### PR TITLE
[10.0][IMP] hr_timesheet_holiday: Allow to use resource calendar to generat…

### PR DESCRIPTION
**Pull request by lmignon**
…e the account analytic lines for a holiday period
implements #177

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@lmignon just to share with you another approach for this if you see it interesting: instead of filling fake timesheets, and have the risk of having a day without real timesheet nor holidays, I developed https://github.com/OCA/hr/tree/10.0/hr_attendance_report_theoretical_time, that computes on the fly theoretical work hours. I'm now migrating it to v12 and will be soon a PR.

**Comment by lmignon** [comment]
@pedrobaeza Thank you for the link. In my UC we need to create specific analytic lines for approved leaves. These lines are used into the computation of the project profitability etc...

**Comment by pedrobaeza** [comment]
OK, then it's not the same UC indeed.

**Comment by lmignon** [comment]
@pedrobaeza Your addon can be useful in other context!
For the record, I also have developed an addon to "autofill" the timesheet sheets with a specific project according to the theoretical work hours. The "autoflled" analytic lines are recomputed each time the TS sheet is modified according to the encoded lines.  If you think it could be useful for others, I can propose it to OCA.

**Comment by pedrobaeza** [comment]
Maybe @alexey-pelykh can be interested, as he is working in something similar in #175

**Comment by alexey-pelykh** [comment]
@lmignon I'm not in position to talk about v10, for v12 in similar UC (leaves => timesheets => AAL) we use `project_timesheet_holidays` with mentioned https://github.com/OCA/hr-timesheet/pull/175

Please elaborate on the UC of autofilling - I don't recall anything similar in my experience

**Comment by lmignon** [comment]
@lmignon In V10 the functionality is not provided by Odoo. It's the purpose of this community addon.

My "Autofilling" addon is a way to automatically generate the AAL to fulfill the theoretical working time for each working day. The goal is to track in an analytic way the time spent outside projects.

**Comment by alexey-pelykh** [comment]
@lmignon to get utilization report of some sort? Or in other words, compare actual time logged vs total theoretical time (or capacity)?

**Review by Cedric-Pigeon — APPROVED** [review]
Code review only

**Pull request closed without merging**
