### PR TITLE
[16.0][MIG] hr_timesheet_time_type

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/timesheet/pull/582

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
Functional review. Tested in runbot. LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by CRogos** [comment]
Could have been nicer. Why is there no label?

image

**Comment by ValentinVinagre** [comment]
> Could have been nicer. Why is there no label?
> 
> image

The label never exist. You are free to make a PR to add the label. We make a new PR to add the label, for the next time you could finish the your pr's :) .

**Pull request merged**
