### PR TITLE
[17.0][MIG] hr_timesheet_sheet: Migration to 17.0

### PR DESCRIPTION
**Pull request by SodexisTeam**
Superseed https://github.com/OCA/timesheet/pull/629

### CODE REVIEW

**Comment by pedrobaeza** [comment]
/ocabot migration hr_timesheet_sheet

Please check CI.

**Comment by valentinthirion** [comment]
Hi there,
What is blocking this PR to be merged?
Thanks in advance,
Best regards

**Comment by valentinthirion** [comment]
Hello,
Can this PR be merged?
Thanks in advance

**Comment by vnikolayev1** [comment]
Hey @valentinthirion @Vijaiy-Selvaraj , did not see your MR, so made my own on porting to 17
There are two ways to fix your MR:
1. Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0. and do updates that are written in the article
History of git blame authors should be kept - do the git format-patch - it's hard to review when git history shows that you added all code.
We should have three commits based on doumentation instructions:
First commit should be pre-commit fixes
Second commit should be porting
Third commit should be your customization

2. you can pull my code, add your customizations with third commit over my code and i review it https://github.com/OCA/timesheet/pull/703

I'd rather do second option, because i've done more things on porting/fixing tests due to documentation and commits are already existing, but it's up to you.

**Comment by vnikolayev1** [comment]
@valentinthirion @Vijaiy-Selvaraj @SodexisTeam are you still interested in review? :)

**Comment by SodexisTeam** [comment]
@vnikolayev1 We took care of the improvements. Please review it.

**Comment by vnikolayev1** [comment]
image
I should see changes that you made, not full commit here ;(
@SodexisTeam please do things that are mentioned in this instruction https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0.

**Comment by vnikolayev1** [comment]
@SodexisTeam Overall porting to 17 looks good after we fix this _check_can_write method , please make migration as 3 commits like in this instruction
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0. 
1st commit you move v16 to v17 with format-patch and do pre-commit (you do pre-commit, than git add everything back what was changed by pre commit than push)
2nd commit should be your port to v17 (run it through pre-commit and do git add)
3rd commit should be your improvements with _check_can_write and report (run it through pre-commit and do git add)

I'll make my MR to yours after that

**Comment by SodexisTeam** [comment]
@vnikolayev1 We took care of the changes. Please review it.

**Comment by vnikolayev1** [comment]
@SodexisTeam Look good, gave another review, Let's wrap it up:
1. Can you please give steps to reproduce _check_can_write bug so I'll check it?
2. Please squash my test fix and suggestions into migration commit (run pre-commit on it)
Let's add our companies so they will be motivated to contribute to OCA

**Comment by SodexisTeam** [comment]
@vnikolayev1 Took care of the changes.

Here is the steps to reproduce _check_can_write bug:

1. Ensure the "project_timesheet_holidays" module is installed.
2. Comment out the "_check_can_write" method in the "account_analytic_line.py" file under the "hr_timesheet_sheet" module.
3. Create a time off request for an employee with a time off type that has "Generate Timesheets" enabled, and approve it.
4. When creating a timesheet for the same employee, if the time off date falls within the timesheet date range, you will encounter a UserError stating: "You cannot modify timesheets that are linked to time off requests. Please use the Time Off application to modify your time off requests instead."

**Comment by vnikolayev1** [comment]
Thank you, will check tomorrow, found another bug on name renderingб added to suggestions:
[hr_timesheet_sheet/models/hr_timesheet_sheet.py](https://github.com/OCA/timesheet/pull/687/files/f7d9b26e6611d305bbeb745b360a269cc1662b67#diff-1f9ae96af55f7b3bc30cba579b3c9a29cefbc335f03e423a75fe2f4c0404d2ae) line 231

**Comment by vnikolayev1** [comment]
Hmm, i see no errors after doing this.
1. Made sure project_timesheet_holidays is installed and commented out _check_can_write function in 
2. Took paid off dayoff
image
image

 and took it for one day 
image
3. added timesheet in analytic account on the same date Menu > Timesheets > All timesheets
image
The only value that going through this method is {'amount': -100.0} , no sheet_id, that's why i thought that this method is kind of sketchy.
Also hasattr(self, "holiday_id") will always be true because we have project_timesheet_holidays module installed
P.S. I only have our modules installed, maybe something else in your project breaks this logic?

**Comment by vnikolayev1** [comment]
@SodexisTeam any thoughts?

**Comment by SodexisTeam** [comment]
@vnikolayev1 

I have attached the error simulation video for your reference. 
Please ensure that the instruction to comment out the _check_can_write method in the account_analytic_line.py file under the hr_timesheet_sheet module has been followed.

[Hr_Timesheet_User_Error.webm](https://github.com/user-attachments/assets/073d6e46-c3f9-48bd-9e61-8259cf0204dc)

**Comment by pedrobaeza** [comment]
Please include #712

**Comment by vnikolayev1** [comment]
@pedrobaeza @SodexisTeam Sorry for taking my time, had urgent project to finish,

 i've just checked module, 
- whenever we change time in timesheet for a day-off we get this error, which makes sense

- LGTM

**Comment by pedrobaeza** [comment]
Please include https://github.com/OCA/timesheet/pull/712 for merging this

**Comment by SodexisTeam** [comment]
@pedrobaeza 

We have included the changes from #712 . Please review them.

**Comment by pedrobaeza** [comment]
I'm not seeing the commit I was referring to. And please remove entirely these 2 commits that are not bringing value:

imagen


You may squash also a little bit the commit history https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

**Comment by SodexisTeam** [comment]
@pedrobaeza 
We have removed the commits, Please review it.
thanks.

**Comment by pedrobaeza** [comment]
There's still no administrative commits squashing, and the attribution of #712 has been lost, but I give up, as it seems you don't want to do it.

It also gets me very nervous to not know to which person I'm talking about. Corporate accounts for me shouldn't be abused committing changes this way. You have organizations for grouping the work of your individuals.

I let other people to do the merge.

**Comment by SodexisTeam** [comment]
@pedrobaeza 

Sorry for the inconvenience caused. 
We ensured that the latest commits of V16 are included in the V17 migrations. 
Thanks

**Comment by pedrobaeza** [comment]
I was talking about squash administrative commits

https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

but OK, let's merge this.

Please check the procedure about this next time, and please do commits with an individual login.

/ocabot merge nobump

**Comment by odoo-sh** [comment]
@pedrobaeza sorry for the trouble and thanks for the comments.  I think we are going to follow your advice and start using individual account, it seemed easier when we started.  Thanks.

**Pull request merged**
