### PR TITLE
[MIG] hr_timesheet_task: Migrated to 10.0

### PR DESCRIPTION
**Pull request by wolh-dynapps**

### CODE REVIEW

**Comment by ghost** [comment]
I proposed the fixes to the code here: https://github.com/Billolha/hr-timesheet/pull/1

otherwise the code looks good to me.

**Comment by ghost** [comment]
@Billolha are you still working on this pull request. Otherwise, tell me and I will take the lead on this. Thanks.

**Comment by wolh-dynapps** [comment]
Hi, unfortunately I won't be able to help you there.
Please take the lead.

Thank you

William Olhasque

Le 22 mars 2017 15:43, David Dufresne <notifications@github.com> a écrit :

@Billolha<https://github.com/Billolha> are you still working on this pull request. Otherwise, tell me and I will take the lead on this. Thanks.

**Comment by cubells** [comment]
@dufresnedavid may I finish this pr or can you do it?

**Pull request closed without merging**
