### PR TITLE
8.0 hr timesheet report with task

### PR DESCRIPTION
**Pull request by lmignon**
Add the column Task in the Timesheet Analysis report

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Great to take new column into account for the analysis!

:+1:

**Comment by sbidoul** [comment]
Thanks Laurent.

Perhaps the group order would be more logical if it was Company, Customer, Analytic Account, Task instead of image

**Comment by lmignon** [comment]
@sbidoul Makes sense. I'll change.

**Comment by lmignon** [comment]
@sbidoul the group 'Customer' doesn't exist for this report in odoo. You probably have extended this report in your project. :smile:

**Comment by sbidoul** [comment]
Indeed.... 

:+1:

**Comment by sbidoul** [comment]
Is this one good for merging?

**Comment by Olivier-LAURENT** [comment]
:+1:

**Pull request merged**
