### PR TITLE
[14.0] [mig] hr_utilization_report

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Comment by dsolanki-initos** [comment]
Hello @pedrobaeza,
Could you review this pull?

**Comment by pedrobaeza** [comment]
Sorry, not using it.

**Comment by dsolanki-initos** [comment]
@elicoidal Could you review this pull?

**Comment by rafaelbn** [comment]
@dsolanki-initos https://odoo-community.org/blog/the-oca-blog-1/post/in-memory-of-eric-caudal-90

**Comment by dsolanki-initos** [comment]
@tarteo Can you please review it?

**Comment by dsolanki-initos** [comment]
@nikul-serpentcs Can you please review this PR?

**Comment by dsolanki-initos** [comment]
@ajaniszewska-dev can you please review this PR?

**Review by ajaniszewska-dev — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
Hello @alexey-pelykh Can we merge this PR?

**Comment by alexey-pelykh** [comment]
Not with checks failing and not enough reviews, sorry

**Comment by dsolanki-initos** [comment]
@AaronHForgeFlow Can you please review this PR?

**Comment by AaronHForgeFlow** [comment]
I am afraid I am not familiar with this module

**Comment by dsolanki-initos** [comment]
@OCA/oca-contributors please review

**Comment by RoelAdriaans** [comment]
Thank you @dsolanki-initos . Finally annoyed me enough to leave the OCA organisation by pinging 1000 man.

**Comment by jeroenev** [comment]
Reminds me of the time when someone notified 400k unreal-engine developers :D
https://github.com/EpicGames/Signup/pull/24#issuecomment-1146718968
Anyway in this case it seems like an innocent mistake, though I wonder why this is the 3rd or 4th time this happened in OCA in 2 weeks
GitHub should allow some groups to be configured as un-pingable.

**Comment by kmatthes** [comment]
@dsolanki-initos Please fix checks first, before asking for an review.

**Comment by dsolanki-initos** [comment]
> @dsolanki-initos Please fix checks first, before asking for an review.

@kmatthes BTW I tried to fix the ci/runbot issue but when I clicked on it and redirected me to goodbye runbot so is there anything for taking care of?

**Comment by simahawk** [comment]
> > @dsolanki-initos Please fix checks first, before asking for an review.
> 
> @kmatthes BTW I tried to fix the ci/runbot issue but when I clicked on it and redirected me to goodbye runbot so is there anything for taking care of?

ignore runbot, is dead ;)

**Comment by alexey-pelykh** [comment]
@simahawk 14.0 branch was updated, this PR would benefit from rebasing then :D

**Review by dreispt — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
Can we merge this PR?

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
