### PR TITLE
[14.0][ADD] hr_timesheet_milestone

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
* Ability to add milestone field
* Widget domain filter for account analytic line

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
This module extends hr_timesheet_report allowing to use field milestone for grouping in timesheet report wizard.

It also relates milestone to analytic line.

---

Functional review ok

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers @alexey-pelykh think we can merge?

**Comment by rafaelbn** [comment]
Just curiosity, where this [icon](hr_timesheet_report_milestone/static/description/icon.png) is printed? Thank you!

**Comment by francesco-ooops** [comment]
@rafaelbn good now? :)

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers what do you say? :)

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers gentle reminder :)

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers @alexey-pelykh @rafaelbn weekly request :)

**Comment by alexey-pelykh** [comment]
I have already reviewed this one, next PSC member who approves it will merge it

**Comment by francesco-ooops** [comment]
> I have already reviewed this one, next PSC member who approves it will merge it

thanks, I was checking documentation once again but can't find where it says 2 reviews from PSC are needed for new modules (I'va had modules merged with one, that's why I tagged you)

**Comment by alexey-pelykh** [comment]
@francesco-ooops see here
https://github.com/OCA/oca-github-bot/blob/master/src/oca_github_bot/tasks/tag_ready_to_merge.py#L31
basically if the PR was green and approved for 5 days - I would've merged it, yet otherwise second approval was usually preferred before - though true that I can not find that guidelines at the moment

**Comment by francesco-ooops** [comment]
@dreispt what happened with bot?

**Comment by francesco-ooops** [comment]
@dreispt could you please try again?

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers @dreispt @alexey-pelykh could you try to launch merge command again? thanks

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers weekly request for merge

**Comment by elvise** [comment]
@pedrobaeza the bot needs some help, can you re-launch ?

**Comment by pedrobaeza** [comment]
Please rebase to see if the CI is wrong

**Comment by elvise** [comment]
@ilyasProgrammer Please rebase

**Comment by elvise** [comment]
> Please rebase to see if the CI is wrong

@pedrobaeza done ✌🏻

**Pull request merged**
