### PR TITLE
[12.0][FIX] hr_timesheet_sheet: tests

### PR DESCRIPTION
**Pull request by alexey-pelykh**
Fixes issue of wrong testing of indeterministic behaviour of merging timesheets.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@astirpe @mreficent I need your help a lot with this: https://travis-ci.org/OCA/timesheet/builds/526910376 builds fail because tests from `sale_timesheet` base module conflict with tests from `hr_timesheet_sheet` about one particular timesheet entry. I'm trying to fix that on my own, but so far I don't understand the context

**Comment by alexey-pelykh** [comment]
To be more precise:
image

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking this. This sounds me that already happened in v11.

**Comment by alexey-pelykh** [comment]
@astirpe do we need to backport this?

**Comment by astirpe** [comment]
Yes, there are not objections by my side :+1:

**Comment by alexey-pelykh** [comment]
Backported as https://github.com/OCA/timesheet/pull/249

**Pull request merged**
