### PR TITLE
[16.0][IMP] hr_timesheet_begin_end: Change line overlap domain from looking for user to employee

### PR DESCRIPTION
**Pull request by dtec-landoo**
With this PR, the only thing I want to change is to replace the user with the employee in the domain. I don't see any logic in checking if the users are the same, since sometimes it can happen that the employee doesn't have a user. In other words, the employee will never be false, whereas the user might be.

### CODE REVIEW

**Review by oo-landoo — APPROVED** [review]
Approved

**Review by rp-landoo — APPROVED** [review]
Functional approval

**Comment by oo-landoo** [comment]
@guewen @luismontalba @ernestotejeda @astirpe @schhatbar-initos Hello, I want to merge the changes into the module. Can someone approve the changes?

**Comment by dtec-landoo** [comment]
@guewen @luismontalba @ernestotejeda @astirpe @schhatbar-initos Hello, I want to merge the changes into the module. Can someone approve the changes?

**Comment by dtec-landoo** [comment]
@pedrobaeza Ready to merge please.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
