### PR TITLE
[14.0] [mig] hr_timesheet_task_stage

### PR DESCRIPTION
**Pull request by dsolanki-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
LGTM. Code review and Functional Tests

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here.

**Comment by dsolanki-initos** [comment]
@ernestotejeda  it would be great if you could add reviews here

**Comment by dsolanki-initos** [comment]
@Yajo It would be great if you could add the reviews here

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here

**Comment by dsolanki-initos** [comment]
It would be great if we could get the reviews here

**Review by ghost — APPROVED** [review]

**Comment by dsolanki-initos** [comment]
It would be nice if the maintainers can merge this PR

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@dsolanki-initos merging will fail due to https://github.com/OCA/timesheet/runs/2959248967
Please re-run precommit pass

**Pull request merged**
