### PR TITLE
[14.0] mig hr timesheet sheet activity

### PR DESCRIPTION
**Pull request by ilyasProgrammer**

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you rather approve this one? https://github.com/OCA/timesheet/pull/543

**Comment by francesco-ooops** [comment]
@ilyasProgrammer can you remove copier code?

**Comment by ilyasProgrammer** [comment]
rebased

**Review by SicurSam — APPROVED** [review]
Functional review ok!

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers could you advise how to fix precommit?

**Comment by Saran440** [comment]
Fixed in https://github.com/OCA/timesheet/pull/538/commits/dfac8213478ab3703f25f4e8e9110e713b6f4969.
Please, update your code again.

**Review by francesco-ooops — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers good for merge?

**Pull request merged**
