### PR TITLE
[12.0][ADD] hr_timesheet_employee_user: sets user from employee

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This is a native feature AFAIK

**Comment by alexey-pelykh** [comment]
@pedrobaeza true, yet only if `employee.user_id` was not changed afterwards the timesheet entry was created/imported

**Comment by pedrobaeza** [comment]
There's an onchange for that. And if not, better to fix it on core.

**Comment by alexey-pelykh** [comment]
My scenario when resetting of that is needed on approx 50k entries. Though I'll address that in core as well

**Comment by pedrobaeza** [comment]
You should use for that mass_editing module with both fields.

**Comment by alexey-pelykh** [comment]
@pedrobaeza got it. Oh well, do what you think it's better with this PR 👍

**Comment by pedrobaeza** [comment]
I think in this case it's better to simply close it, as it's better to not convert OCA repositories into bloatware :wink:

**Comment by alexey-pelykh** [comment]
Indeed, this time this was an overkill taking into account `mass_editing`. Thanks for keeping repos clean 💯 !

**Pull request closed without merging**
