### PR TITLE
[12.0][FIX]hr_utilization_report: when field is empty #310

### PR DESCRIPTION
**Pull request by yousef-soliman**
related to #310

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@yousef-soliman thanks for contribution! What would be the test data for such case? As far as I can see from https://github.com/odoo/odoo/blob/39e97052b8946e7b13ce5e8bf096962d712cb130/odoo/addons/base/models/ir_qweb_fields.py#L126 it's a possible case nevertheless.

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by alexey-pelykh** [comment]
It would be great to have a test case for such occasion, maybe something else will ever break, yet that's optional

**Comment by yousef-soliman** [comment]
@alexey-pelykh 
i have added a test case in tests 
should i make new pull request ?

**Comment by alexey-pelykh** [comment]
Yep, please do so and I'll merge that one as well

**Pull request merged**
