### PR TITLE
[MIG][10.0] hr_employee_product

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Migration from 8 to 10.

PR in v8 is not merged: https://github.com/OCA/hr-timesheet/pull/35

### CODE REVIEW

**Comment by rami-wafaie** [comment]
Tested it, It looks fine for me 
:+1:

**Comment by pedrobaeza** [comment]
Please use current GitHub approval method (you have it on the third tab)

**Review by rami-wafaie — APPROVED** [review]
:+1:

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, LGTM :+1:

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Pull request merged**
