### PR TITLE
[12.0][FIX] hr_timesheet_sheet: Reviewers must be HR managers, not officers

### PR DESCRIPTION
**Pull request by pedrobaeza**
Current reviewer group is "Employees/Officer", which doesn't belong to the semantics of the review policy, and it's also too verbose.

@Tecnativa TT25181

### CODE REVIEW

**Comment by pedrobaeza** [comment]
@alexey-pelykh @astirpe can you review?

Another question? Why always subscribe system user? I was about to remove that line if you consider so (or at least on default policy, don't add it).

**Comment by alexey-pelykh** [comment]
@pedrobaeza I doubt it's a valid change as "HR Manager" has too many permissions and is sort of closer to "HR Director", or lead of entire department. Unlikely that person actually does reviews.

**Comment by pedrobaeza** [comment]
I don't agree, as HR manager fits all the requirements. Anyway, if that's the problem, then let's create 2 review policy in this module: `hr` and `hr_manager`, and change the redaction of the review policy text. @astirpe what's your opinion?

Other option is to use "Timesheet / Responsible" group.

**Comment by alexey-pelykh** [comment]
@pedrobaeza I totally support more clarification, so adding extra policy would be great and very backward compatible. And having even 3 (including "Timesheet / Responsible") won't hurt

**Comment by astirpe** [comment]
I agree with the "backward compatible" approach by allowing the `hr` and `hr_manager` policy.
The "Timesheet / Responsible" is not necessary here IMO, as the modules `hr_timesheet_sheet_policy_*` do the job in a more appropriate way.

Very important thing: keep allowing the system user (admin) to review timesheets. This was helpful in countless situations for our customers and support service.

**Comment by pedrobaeza** [comment]
OK, added then `hr_manager`. I have also added the Timesheets manager one, as reviewing the mentioned hr_timesheet_policy_*, I don't see any equivalent.

I have also kept the system follower, but I still don't understand how is that helpful.

**Comment by astirpe** [comment]
Not really necessary, but I'm pointing it out anyway: in file `DESCRIPTION.rst` still it's written:
`By default ... HR Officer/Manager as reviewer.`.
Should be `HR Officers` after latest modification.

**Comment by pedrobaeza** [comment]
Good note. Changed the README and added a note talking about extra review policy modules.

**Review by astirpe — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Thanks both for the quick response:

/ocabot merge patch

**Pull request merged**
