### PR TITLE
[14.0][FIX] hr_timesheet_sheet: Re-use original arguments

### PR DESCRIPTION
**Pull request by ypapouin**
Two seconds review
@Volodiay616

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@ypapouin please port the fix over to other versions

**Comment by ypapouin** [comment]
The original `[IMP] hr_timesheet_sheet: prevent sending emails` commit only exists in 14.0

**Comment by alexey-pelykh** [comment]
thanks for looking into that!

**Pull request merged**
