### PR TITLE
[ADD] when approving a timesheet, create leaves if necessary

### PR DESCRIPTION
**Pull request by hbrunn**

### CODE REVIEW

**Comment by feketemihai** [comment]
@hbrunn Hi, this is a good improvement, but is it worth it..since by default you already schedule holidays before, do you have situations where this apply?

**Comment by hbrunn** [comment]
my customer works like that. they don't really use the holiday workflow, only to assign the amount of holidays. and they don't register holidays in advance, you basically request your holidays afterwards by submitting timesheets

**Comment by feketemihai** [comment]
@hbrunn Can we have this behaviour based on a configuration checkbox, not to be implicit?

**Comment by hbrunn** [comment]
I think this is a quite logical continuation of the original goal of the module: Make analytic lines equivalent with holidays. So I don't really see the need for hiding this behind the config parameter.

**Review by rafaelbn — APPROVED** [review]
:+1:

**Review by feketemihai — APPROVED** [review]

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
