### PR TITLE
{14.0}[PORT] 363 from 12.0 [FIX] project_timesheet_time_control: incompatible with sale_timesheet_rounded

### LINKED ISSUE #464: Error on pressing "start working"
I must be missing something or it is a bug?
I created a new project, then a new task then pressed to "start working" so it starts counting the time consumed in working on this task.
Screen Shot 2021-10-13 at 11 42 01 PM
as the above pic shows.
then it raises an error.
Screen Shot 2021-10-13 at 11 42 21 PM
I will also list the error below.

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo14ce/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo14ce/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo14ce/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo14ce/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo14ce/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo14ce/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo14ce/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo14ce/custom/addons/project_timesheet_time_control/wizards/hr_timesheet_switch.py", line 143, in action_switch
    self.read(_fields)
  File "/opt/odoo14ce/custom/addons/sale_timesheet_rounded/models/account_analytic_line.py", line 97, in read
    fields_local = fields.copy() if fields else []
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo14ce/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14ce/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'odict_keys' object has no attribute 'copy'

### PR DESCRIPTION
**Pull request by bosd**
{#363} from 12.0 to 14.0
fixes https://github.com/OCA/timesheet/issues/464

### CODE REVIEW

**Comment by bosd** [comment]
@CasVissers-360ERP Would you be so kind to review this one? :pray:

**Comment by bosd** [comment]
Locally pre-commit is green. How to get it to green here?

**Comment by bosd** [comment]
Oke, force pushing seems to have solved it.

/ocabot tag_needs_review

**Review by flotho — APPROVED** [review]
LGTM

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
