### PR TITLE
[14.0][FIX] hr_timesheet_sheet - Do not merge invoiced timesheet lines

### PR DESCRIPTION
**Pull request by bosd**
Continuation of #462 now with pre-commit.

### CODE REVIEW

**Comment by bosd** [comment]
closes https://github.com/OCA/timesheet/issues/463

**Review by flotho — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
@alexey-pelykh  would you be so kind to review this one?

**Review by flotho — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Pull request merged**
