### PR TITLE
[17.0][MIG] hr_timesheet_begin_end: Migration to 17.0

### PR DESCRIPTION
**Pull request by NICO-SOLUTIONS**
standard migration to 17.0

### CODE REVIEW

**Comment by MohamedOsman7** [comment]
Everything looks good to me. However, i noticed a warning in the test, that should be addressed.

"2024-02-04 10:45:04,497 237 WARNING odoo py.warnings: /opt/odoo/odoo/addons/base/models/ir_module.py:178: DeprecationWarning: XML declarations in HTML module descriptions are deprecated since Odoo 17, hr_timesheet_begin_end can just have a UTF8 description with not need for a declaration."

**Comment by NICO-SOLUTIONS** [comment]
This will be fixed by pre commit when adjusted to not create encoding in Index file!

**Review by MohamedOsman7 — APPROVED** [review]

**Review by CRogos — COMMENTED** [review]
I've updated the copier template. A rebase should solve the warning.
The rest looks good to me.

**Comment by NICO-SOLUTIONS** [comment]
@CRogos  thanks for updating the copier. rebased and ready for further review...

**Review by CRogos — APPROVED** [review]

**Pull request merged**
