### PR TITLE
[14.0] [mig] hr_timesheet_activity_begin_end

### PR DESCRIPTION
**Pull request by schhatbar-initos**

### CODE REVIEW

**Review by fshah-initos — APPROVED** [review]
Code review and functional tests. LGTM

**Comment by schhatbar-initos** [comment]
@astirpe Can you please review this PR?
Thanks in Advance!

**Comment by schhatbar-initos** [comment]
@pedrobaeza Can you review this PR?
Thanks in Advance!

**Comment by schhatbar-initos** [comment]
@pedrobaeza  Can you please review this PR?
Thanks in Advance!

**Comment by pedrobaeza** [comment]
You should review other PRs and ask in exchange that they review yours.

**Comment by schhatbar-initos** [comment]
@all Can you please review the PR?

**Review by bosd — APPROVED** [review]
LGTM :+1:

**Comment by dsolanki-initos** [comment]
It would be great if we could merge the PR.

**Comment by bosd** [comment]
Hello @OCA\/timesheet-maintainers  can we merge this?
Why is the @OCA\timesheet-maintainers not working?

**Comment by dsolanki-initos** [comment]
It would be great if we could merge this PR.

**Comment by dsolanki-initos** [comment]
Seems that PR is approved is it poosible to get merge it?

**Comment by dsolanki-initos** [comment]
It would be nice if maintainers could merge the PR.

**Pull request merged**
