### PR TITLE
[12.0][IMP] hr_timesheet_sheet: department, direct, and project reviewers

### PR DESCRIPTION
**Pull request by alexey-pelykh**
@CasVissers @i-vyshnevska @artemsenko this PR adds department, direct, and project-level reviewers. This can be implemented as 3 separate modules, if really needed @mreficent

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
+ @aheficent

**Comment by AaronHForgeFlow** [comment]
This is working fine to me. However, I will let the maintainer  of the module to review first :sweat_smile:

**Comment by alexey-pelykh** [comment]
@aheficent and that is..? Maintainer not declared in module, while should be

**Comment by AaronHForgeFlow** [comment]
Originally, @mreficent and @astirpe  did the most of the work originally. I thought they were maintainters. :smile:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Code + Functional. 
Thank you @alexey-pelykh

**Review by artemsenko — APPROVED** [review]
functional test

**Comment by alexey-pelykh** [comment]
@mreficent @astirpe sorry to bother, yet it would be wonderful if I could get slice of your time for this PR

**Comment by astirpe** [comment]
@alexey-pelykh I think this is a good functional addition, thanks!

 However my opinion is always the same: module `hr_timesheet_sheet` should be just a basic module implementing the weekly/monthly timesheet sheet with the overall matrix view. Nothing more.

Unfortunately the `hr_timesheet_sheet` became already too bloated and the trend of adding new features seems not going to stop soon.
I will not update the module at our customers, to avoid the risk to break something. So I'm not interested in reviewing this PR.

Instead if you can create a separate module for this functionality, then I could try to find some time to review it.

**Comment by alexey-pelykh** [comment]
@astirpe right now I tend to agree with you, yet there will have to be 3 modules, one per policy
`hr_timesheet_sheet_department`
`hr_timesheet_sheet_direct`
`hr_timesheet_sheet_project`
?
Are we all ok with the naming?

**Comment by MiquelRForgeFlow** [comment]
> Are we all ok with the naming?

yes, why not?

**Comment by alexey-pelykh** [comment]
Superseded by https://github.com/OCA/timesheet/pull/289

**Pull request closed without merging**
