### PR TITLE
[11.0] hr_timesheet_sheet: add menu 'Timesheet Sheets to Approve'

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This menu was missing:

image

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @Eficent

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
change number version

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional test

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
It seems at the end that the version number bumping is not so important according @sbidoul, so I merge as is.

**Pull request merged**
