### PR TITLE
[14.0] [mig] hr_timesheet_task_required

### PR DESCRIPTION
**Pull request by fshah-initos**

### CODE REVIEW

**Review by dsolanki-initos — APPROVED** [review]
No major change.

**Comment by fshah-initos** [comment]
@astirpe will you please review this PR?

**Comment by fshah-initos** [comment]
@alexey-pelykh Will you please review this PR?

**Review by alexey-pelykh — APPROVED** [review]
Code LGTM

**Comment by fshah-initos** [comment]
@alexey-pelykh Thank you for the review!
Will you please merge it as well ?

**Comment by fshah-initos** [comment]
@OCA/human-resources-maintainers  is it possible to merge it as it is approved?

**Pull request merged**
