### PR TITLE
[12.0][IMP] Move "My Timesheet Sheets" lower than "My Timesheets"

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This allows to maintain the original behavior of "Timesheets" menu item.

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@bjeficent @aheficent I think you're using this module a lot, thus it would be great to get your feedback on this change

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
If you have hr_timesheet_sheet installed you want that `My timesheet Sheets` be on the top because users will normally uses that view to fill timesheet. Moreover, when that module was part of Odoo community that menu was always on the top. I don't see then the reason for installing it the module.

**Comment by alexey-pelykh** [comment]
Hmmm, got it. I was thinking about other approach when "My Timesheets" are used on a daily basis and "My timesheet Sheets" are used weekly to submit entries entered via "My Timesheets". Am I missing something?

**Comment by AaronHForgeFlow** [comment]
I guess you can use both on a daily basis, but as I said, when hr_timesheet_sheet module was part of Odoo community it was always on first place. Maybe we can create an issue if more people agree with your idea...

**Comment by alexey-pelykh** [comment]
I guess that's the only proper way to proceed 👍 Any guide on doing that?

**Comment by AaronHForgeFlow** [comment]
Well, actually, as this PR is already created maybe we can use this one to discuss.

Ping @OCA/human-resources-maintainers

**Comment by alexey-pelykh** [comment]
It turns out that with #154 this one is not needed

**Pull request closed without merging**
