### PR TITLE
[12.0][IMP] hr_timesheet_sheet: timesheet_sheet_ids on hr.employee

### PR DESCRIPTION
**Pull request by carmenbianca**
Fairly simple contribution. I need this field downstream, and I figured it'd be useful upstream.

### CODE REVIEW

**Comment by carmenbianca** [comment]
Bump

**Review by alexey-pelykh — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
Runboat is failing

This is a improvement [IMP]! 😄 thank you!

LGTM! 👍

**Comment by carmenbianca** [comment]
Changed the commit message to IMP :+1:

**Review by norlinhenrik — APPROVED** [review]

**Comment by nimarosa** [comment]
@carmenbianca Please rebase the PR to trigger checks again and we can merge. Can't do it because you didn't allow changes by maintainers.

**Review by nimarosa — APPROVED** [review]

**Comment by carmenbianca** [comment]
@nimarosa Rebased. Not sure how I can retroactively grant permissions.

**Comment by carmenbianca** [comment]
And the check is broken because the template is outdated, I believe. I'll fix that.

**Pull request merged**
