### PR TITLE
[15.0][MIG]hr_timesheet_sheet_policy_project_manager : Migration to V15

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Review by Yadier-Tecnativa — APPROVED** [review]

**Comment by Yadier-Tecnativa** [comment]
You should merge/squash commits generated by bots or Weblate so that the commit history contains the minimum necessary messages.

**Comment by Yadier-Tecnativa** [comment]
ping @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Let's merge and you can do the squashing on 16.0 migration, which is the one that will continue upward.

/ocabot merge nobump

**Comment by pedrobaeza** [comment]
It seems there's a problem in the branch.

**Pull request merged**
