### PR TITLE
[14.0][MIG] sale_timesheet_order_line_sync: Migration to 14.0

### PR DESCRIPTION
**Pull request by victoralmau**
Migration to 14.0

Please @joao-p-marques and @carlosdauden can you review it?

@Tecnativa TT30303

### CODE REVIEW

**Review by carlosdauden — APPROVED** [review]
Is it still necessary? Odoo has not solved this problem?

**Comment by victoralmau** [comment]
> Is it still necessary? Odoo has not solved this problem?

this addon will not be necessary if the project is configured like this: https://github.com/odoo/odoo/blob/14.0/addons/sale_timesheet/models/project.py#L40 now the sales line is defined like this: https://github.com/odoo/odoo/blob/14.0/addons/sale_timesheet/models/project.py#L330 

I do not know all the use cases, but with this in mind, in my opinion this addon would not be necessary. what do you think?

**Comment by pedrobaeza** [comment]
The code you link is acting when you change on the task the mark "Non-Billable", but not when you change the SO line, so I think this is still needed.

**Review by pedrobaeza — APPROVED** [review]

**Review by hkapatel-initos — APPROVED** [review]
Code review and check functionality: LGTM

**Pull request merged**
