### PR TITLE
[14.0][FIX] hr_utilization_report: missing _description

### PR DESCRIPTION
**Pull request by sergiocorato**

### CODE REVIEW

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
@sergiocorato would you mind bringing this fix to other versions as well?

**Comment by sergiocorato** [comment]
> @sergiocorato would you mind bringing this fix to other versions as well?

What versions? This module seems un-ported

**Comment by alexey-pelykh** [comment]
@sergiocorato and previous versions?

**Comment by sergiocorato** [comment]
> @sergiocorato and previous versions?

v. 12.0 perhaps?

**Comment by alexey-pelykh** [comment]
> v. 12.0 perhaps?

yep!

**Pull request merged**
