### PR TITLE
[16.0] [mig] hr_timesheet_sheet_policy_department_manager

### PR DESCRIPTION
**Pull request by edlopen**
Migration to 16.0 with some changes to the tests.

@moduon MT-1703

@yajo @EmilioPascual @Shide @rafaelbn @fcvalgar review this PR when you can. Thank you!

### CODE REVIEW

**Review by fcvalgar — APPROVED** [review]
Functional review.

LGTM, Thank you @edlopen 

image

image

image

**Review by EmilioPascual — APPROVED** [review]
LGTM. Functional and code review
Nice job @edlopen

**Review by alexey-pelykh — APPROVED** [review]

**Comment by alexey-pelykh** [comment]
/ocabot migration hr_timesheet_sheet_policy_department_manager

**Pull request merged**
