### PR TITLE
[12.0][ADD] hr_timesheet_employee_cost_contract

### PR DESCRIPTION
**Pull request by alexey-pelykh**
This module implements automatic computation of Employee Cost based on
contracts.

image

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
@pedrobaeza @AaronHForgeFlow @astirpe maybe you'd be interested in using such module?

**Review by sweenya — APPROVED** [review]
Functional test

**Review by YegorOkhotnikov — APPROVED** [review]
Functional test

**Pull request merged**
