### PR TITLE
[14.0][FIX] sale_timesheet_line_exclude, remove non_allow_billable inheritance

### PR DESCRIPTION
**Pull request by GSLabIt**

### CODE REVIEW

**Comment by CRogos** [comment]
What is the reason for this change? 
Could you have a look at this fix for v15. I think we are facing the same issue: https://github.com/OCA/timesheet/pull/540

exclude_from_sale_order and non_allow_billable should be in sync and both be displayed as non-billable. 
To prevent both columns to be shown, we need to remove one. 

"non_allow_billable" was new with Odoo 14 and is discontinued on Odoo 15. Therefore I think overwriting the standard is OK.

**Comment by GSLabIt** [comment]
> What is the reason for this change?
> 
> exclude_from_sale_order and non_allow_billable should be in sync and both be displayed as non-billable. To prevent both columns to be shown, we need to remove one.
> 
> "non_allow_billable" was new with Odoo 14 and is discontinued on Odoo 15. Therefore I think overwriting the standard is OK.

for some reason the field `non_allow_billable` has been removed from `hr_timesheet.timesheet_view_tree_user` in v `14.0`:

https://github.com/odoo/odoo/blob/858f9d2625b81b3efbd6dfe40360eea2d9aa75da/addons/hr_timesheet/views/hr_timesheet_views.xml#L38-L52

and from:

https://github.com/odoo/odoo/blob/858f9d2625b81b3efbd6dfe40360eea2d9aa75da/addons/hr_timesheet/views/hr_timesheet_views.xml#L21-L36

**Comment by CRogos** [comment]
Would replacing 
`<field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />`
by 
`<field name="inherit_id" ref="hr_timesheet.hr_timesheet_line_tree" />`

fix your issue?

**Comment by GSLabIt** [comment]
> Would replacing `<field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />` by `<field name="inherit_id" ref="hr_timesheet.hr_timesheet_line_tree" />`
> 
> fix your issue?

Nope, `non_allow_billable` is nowhere in hr_timesheet view. Have a look at:

https://github.com/odoo/odoo/blob/858f9d2625b81b3efbd6dfe40360eea2d9aa75da/addons/hr_timesheet/views/hr_timesheet_views.xml#L38-L52

and from:

https://github.com/odoo/odoo/blob/858f9d2625b81b3efbd6dfe40360eea2d9aa75da/addons/hr_timesheet/views/hr_timesheet_views.xml#L21-L36

**Comment by CRogos** [comment]
And the exclude_from_sale_order field is not stuffient for your purpose`?
I did remove non_allow_billable, because this field is only available in Odoo v14 and was removed with Odoo 15.
My idea while migration to v14 merge the feature of this module with non_allow_billable. If you show non_allow_billable, you have two columns named "Non-billable" one from Odoo 14 and one from this module. I think this is also confusing.

But again, I think moving exclude_from_sale_order to hr_timesheet.hr_timesheet_line_tree might help? https://github.com/OCA/timesheet/pull/540

**Comment by GSLabIt** [comment]
> And the exclude_from_sale_order field is not stuffient for your purpose`? I did remove non_allow_billable, because this field is only available in Odoo v14 and was removed with Odoo 15. My idea while migration to v14 merge the feature of this module with non_allow_billable. If you show non_allow_billable, you have two columns named "Non-billable" one from Odoo 14 and one from this module. I think this is also confusing.
> 
> But again, I think moving exclude_from_sale_order to hr_timesheet.hr_timesheet_line_tree might help? #540

Can you tell me where is the field `non_allow_billable` in this view, because it seems i'm becoming blind ..

```
        <record id="hr_timesheet_line_tree" model="ir.ui.view">
            <field name="name">account.analytic.line.tree.hr_timesheet</field>
            <field name="model">account.analytic.line</field>
            <field name="arch" type="xml">
                <tree editable="bottom" string="Timesheet Activities" sample="1">
                    <field name="date"/>
                    <field name="employee_id" invisible="1"/>
                    <field name="project_id" required="1" options="{'no_create_edit': True, 'no_open': 1}"/>
                    <field name="task_id" optional="show" options="{'no_create_edit': True, 'no_open': True}" widget="task_with_hours" context="{'default_project_id': project_id}"/>
                    <field name="name" optional="show" required="0"/>
                    <field name="unit_amount" optional="show" widget="timesheet_uom" sum="Total" decoration-danger="unit_amount &gt; 24 or unit_amount &lt; 0"/>
                    <field name="company_id" invisible="1"/>
                    <field name="user_id" invisible="1"/>
                </tree>
            </field>
        </record>
```

If you try to inherit, you'll get an error.

**Comment by CRogos** [comment]
Ok now I see your problem. 
I mean replace 
```
    <record id="account_analytic_line_tree_user" model="ir.ui.view">
        <field name="name">account.analytic.line.tree.user</field>
        <field name="model">account.analytic.line</field>
        <field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='task_id']" position="after">
                <field name="exclude_from_sale_order" optional="show" />
            </xpath>
            <xpath expr="//field[@name='non_allow_billable']" position="attributes">
                <attribute name="attrs">{'invisible': True}</attribute>
            </xpath>
        </field>
    </record>
```
by
```
    <record id="account_analytic_line_tree_user" model="ir.ui.view">
        <field name="name">account.analytic.line.tree.user</field>
        <field name="model">account.analytic.line</field>
        <field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='non_allow_billable']" position="attributes">
                <attribute name="attrs">{'invisible': True}</attribute>
            </xpath>
        </field>
    </record>
    <record id="hr_timesheet_line_tree" model="ir.ui.view">
        <field name="name">account.analytic.line.tree.user</field>
        <field name="model">account.analytic.line</field>
        <field name="inherit_id" ref="hr_timesheet.hr_timesheet_line_tree" />
        <field name="arch" type="xml">
            <xpath expr="//field[@name='task_id']" position="after">
                <field name="exclude_from_sale_order" optional="show" />
            </xpath>
        </field>
    </record>
```

(havn't tested yet)

**Comment by GSLabIt** [comment]
> Ok now I see your problem. I mean replace
> 
> ```
>     <record id="account_analytic_line_tree_user" model="ir.ui.view">
>         <field name="name">account.analytic.line.tree.user</field>
>         <field name="model">account.analytic.line</field>
>         <field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />
>         <field name="arch" type="xml">
>             <xpath expr="//field[@name='task_id']" position="after">
>                 <field name="exclude_from_sale_order" optional="show" />
>             </xpath>
>             <xpath expr="//field[@name='non_allow_billable']" position="attributes">
>                 <attribute name="attrs">{'invisible': True}</attribute>
>             </xpath>
>         </field>
>     </record>
> ```
> 
> by
> 
> ```
>     <record id="account_analytic_line_tree_user" model="ir.ui.view">
>         <field name="name">account.analytic.line.tree.user</field>
>         <field name="model">account.analytic.line</field>
>         <field name="inherit_id" ref="hr_timesheet.timesheet_view_tree_user" />
>         <field name="arch" type="xml">
>             <xpath expr="//field[@name='non_allow_billable']" position="attributes">
>                 <attribute name="attrs">{'invisible': True}</attribute>
>             </xpath>
>         </field>
>     </record>
>     <record id="hr_timesheet_line_tree" model="ir.ui.view">
>         <field name="name">account.analytic.line.tree.user</field>
>         <field name="model">account.analytic.line</field>
>         <field name="inherit_id" ref="hr_timesheet.hr_timesheet_line_tree" />
>         <field name="arch" type="xml">
>             <xpath expr="//field[@name='task_id']" position="after">
>                 <field name="exclude_from_sale_order" optional="show" />
>             </xpath>
>         </field>
>     </record>
> ```
> 
> (havn't tested yet)

did u ever reviewed the code instead?

**Comment by CRogos** [comment]
> did u ever reviewed the code instead?

Yes I did a lot on this code, but there were a lot of changes necessary between v13/v14/v15.

https://github.com/OCA/timesheet/pull/510
https://github.com/OCA/timesheet/pull/510/commits/9e74784552dce536b8d935a1bde9e419e7de4ff0

however do what you want to do... I am not using Odoo 14 anymore anyway.

**Review by francesco-ooops — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@OCA/human-resources-maintainers could you please review? thanks :)

**Comment by nimarosa** [comment]
@francesco-ooops pre-commit is failing so you have to fix that to proceed.

**Comment by francesco-ooops** [comment]
@GSLabIt can you make a PR to update copier, something like https://github.com/OCA/oca-addons-repo-template/pull/170 ?

thanks

**Comment by CRogos** [comment]
@francesco-ooops  you mean this: https://github.com/OCA/timesheet/pull/543
I think only a rebase is necessary.

But I still think this change is not good because it causes two columns with the same content in the list view.
image

**Comment by francesco-ooops** [comment]
@CRogos but the PR has just been rebased, this is another precommit issue due to a link to gitlab, so I think another fix is necessary

**Comment by nimarosa** [comment]
I tought template is updated but will test when i have time, if not, i will update it and rebase this.

**Comment by GSLabIt** [comment]
> I tought template is updated but will test when i have time, if not, i will update it and rebase this.

just review and merge this one

**Review by nimarosa — APPROVED** [review]

**Comment by nimarosa** [comment]
Aborted, wrong bump. 
Let's go again. 

/ocabot merge patch

**Pull request merged**
