### PR TITLE
[11.0][FIX] hr_timesheet_sheet: wrong decorator

### PR DESCRIPTION
**Pull request by astirpe**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by tarteo — APPROVED** [review]

**Review by alexey-pelykh — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Is this applicable to v12?

**Comment by alexey-pelykh** [comment]
@pedrobaeza yes

**Comment by pedrobaeza** [comment]
Cherry-picked (kind of) for v12 in b9a8657b31b8124719aff548e59dfe5dc8539217

**Comment by MiquelRForgeFlow** [comment]
Did you solved the hr_timesheet_sheet_attendance travis error?

**Pull request merged**
