### PR TITLE
[12.0][MIG] hr_timesheet_task_required

### PR DESCRIPTION
**Pull request by alexey-pelykh**

### CODE REVIEW

**Comment by alexey-pelykh** [comment]
Good people of 11.0 and 10.0 PRs, please review this one as well @feketemihai @benwillig @lreficent

**Review by nikul-serpentcs — APPROVED** [review]
Code Review LGTM

**Comment by alexey-pelykh** [comment]
Now this feature is configurable on per-project basis

**Comment by alexey-pelykh** [comment]
@benwillig as author of previous migrations, please review

**Comment by alexey-pelykh** [comment]
@adrienpeiffer as author, please review, if you don't mind

**Comment by alexey-pelykh** [comment]
@pedrobaeza @aheficent is there interest from your side towards this module/improvement?

**Review by pedrobaeza — APPROVED** [review]
Code review

**Pull request merged**
